export const ListData= [{
  id: '1',
  registNumber: '2017101021221',
  officialName: "Wal-Mart Stores",
  scb: 'No',
  mode:'B',
  whiteListStatus:'Normal',
  auditStatus:'APPROVED',
}, {
  id: '2',
  registNumber: '2017101021222',
  officialName: "Wal-Mart Jsonc",
  scb: 'No',
  mode:'A',
  whiteListStatus:'Normal',
  auditStatus:'REJECT',
}, {
  id: '3',
  registNumber: '2017101021223',
  officialName: "Wal-Mart Toms",
  scb: 'No',
  mode:'A',
  whiteListStatus:'Normal',
  auditStatus:'REJECT',
}, {
  id: '4',
  registNumber: '2017101021224',
  officialName: "Wal-Mart WAAT",
  scb: 'No',
  mode:'C',
  whiteListStatus:'Normal',
  auditStatus:'REJECT',
},{
  id: '5',
  registNumber: '2017101021225',
  officialName: "Wal-Mart WeiSmith",
  scb: 'No',
  mode:'C',
  whiteListStatus:'Normal',
  auditStatus:'other',
},{
  id: '6',
  registNumber: '2017101021226',
  officialName: "Wal-Mart Who",
  scb: 'No',
  mode:'C',
  whiteListStatus:'Normal',
  auditStatus:'REJECT',
},
  {
    id: '7',
    registNumber: '2017101021227',
    officialName: "Wal-Mart",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'PENDING',
  },
  {
    id: '8',
    registNumber: '2017101021228',
    officialName: "Wal-Mart",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'APPROVED',
  }, {
    id: '9',
    registNumber: '2017101021229',
    officialName: "Mister Wal-Mart ",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'REJECT',
  },
  {
    id: '10',
    registNumber: '2017101021230',
    officialName: "Wal-Mart Gard",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'PENDING',
  },
  {
    id: '11',
    registNumber: '2017101021231',
    officialName: "Wal-Mart Jackson",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'REJECT',
  },
  {
    id: '12',
    registNumber: '2017112800001',
    officialName: "Wal-Mart Jackson",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'REJECT',
  },
  {
    id: '13',
    registNumber: '2017112800002',
    officialName: "Wal-Mart Jackson",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'REJECT',
  },
  {
    id: '14',
    registNumber: '2017112800003',
    officialName: "Wal-Mart Jackson",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'REJECT',
  },
  {
    id: '15',
    registNumber: '2017112800004',
    officialName: "Wal-Mart Jackson",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'REJECT',
  },
  {
    id: '16',
    registNumber: '2017112800005',
    officialName: "Wal-Mart Jackson",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    auditStatus:'REJECT',
  },
  ];
