export const ListData= [{
  key: '1',
  number: '2017101021221',
  companyName: "Wal-Mart Stores",
  scb: 'No',
  mode:'B',
  whiteListStatus:'Normal',
  opsStatus:'Approve',
}, {
  key: '2',
  number: '2017101021222',
  companyName: "Wal-Mart Jsonc",
  scb: 'No',
  mode:'A',
  whiteListStatus:'Normal',
  opsStatus:'Reject',
}, {
  key: '3',
  number: '2017101021223',
  companyName: "Wal-Mart Toms",
  scb: 'No',
  mode:'A',
  whiteListStatus:'Normal',
  opsStatus:'Reject',
}, {
  key: '4',
  number: '2017101021224',
  companyName: "Wal-Mart WAAT",
  scb: 'No',
  mode:'C',
  whiteListStatus:'Normal',
  opsStatus:'Reject',
},{
  key: '5',
  number: '2017101021225',
  companyName: "Wal-Mart WeiSmith",
  scb: 'No',
  mode:'C',
  whiteListStatus:'Normal',
  opsStatus:'Reject',
},{
  key: '6',
  number: '2017101021226',
  companyName: "Wal-Mart Who",
  scb: 'No',
  mode:'C',
  whiteListStatus:'Normal',
  opsStatus:'Reject',
},
  {
    key: '7',
    number: '2017101021227',
    companyName: "Wal-Mart",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    opsStatus:'Pending Approve',
  },
  {
    key: '8',
    number: '2017101021228',
    companyName: "Wal-Mart",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    opsStatus:'Approve',
  }, {
    key: '9',
    number: '2017101021229',
    companyName: "Mister Wal-Mart ",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    opsStatus:'Reject',
  },
  {
    key: '10',
    number: '2017101021230',
    companyName: "Wal-Mart Gard",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    opsStatus:'Approve',
  },
  {
    key: '11',
    number: '2017101021231',
    companyName: "Wal-Mart Jackson",
    scb: 'No',
    mode:'C',
    whiteListStatus:'Normal',
    opsStatus:'Reject',
  }];
