var Mock=require("mockjs");
import UrlConfig from '../../common/config/addressConfig';
Mock.mock(UrlConfig().userManagerUrl, [{
    "id": "1",
    "name": "张三",
    "telphone": "178956878",
    "city": "上海",
    "departmentName": "技术部",
    "isActived": "已启用",
    "createdTime": "2017-10-1"
},
    {
        "id": "2",
        "name": "李四",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已启用",
        "createdTime": "2017-10-1"
    }, {
        "id": "3",
        "name": "王五",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }, {
        "id": "4",
        "name": "太子",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }, {
        "id": "5",
        "name": "王菲",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }, {
        "id": "6",
        "name": "窦唯",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }, {
        "id": "7",
        "name": "康熙",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }, {
        "id": "8",
        "name": "王国维",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }, {
        "id": "9",
        "name": "文章",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }, {
        "id": "10",
        "name": "乔丹",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }, {
        "id": "11",
        "name": "Smith",
        "telphone": "178956878",
        "city": "上海",
        "departmentName": "技术部",
        "isActived": "已禁用",
        "createdTime": "2017-10-1"
    }]);